### ISSUE TITLE
Run Commands Given Return A Python Error

### ISSUE THREAD

**Issue by solisa986** [ProactiveProgrammers/iterative-exponentiation-starter#1]
The current run commands:
- ```poetry run python iterator --forloop --whileloop --minimum 0 --maximum 5```
- ```poetry run python iterator --forloop --minimum 0 --maximum 5```
- ```poetry run iterator --whileloop --minimum 2 --maximum 10```

These run commands contain 'python' in the command, which is not meant to be run alongside poetry. In order to run the program accurately, the run commands should be modified to:
- ```poetry run iterator --forloop --whileloop --minimum 0 --maximum 5```
- ```poetry run iterator --forloop --minimum 0 --maximum 5```
- ```poetry run iterator --whileloop --minimum 2 --maximum 10```

This will allow the user to run the iterator program without getting errors with the run command.

**Comment by gkapfham** [comment]
Hello @solisa986, thanks for raising this issue! I have fixed all of these problems in the current version of the repository. If you find any additional problems or if you think that I have not resolved this issue correctly, please let me know and consider reopening the issue. Thanks again for taking the time to resolve this problem!
